version: "3.7"

services:
  bot:
    build: 
      context: .
      dockerfile: bot.Dockerfile
    command: python main.py
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./docker.env
    depends_on:
      - db
  db:
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=argenta
      - POSTGRES_INITDB_ARGS=-E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'
    build:
      context: .
      dockerfile: db.Dockerfile

volumes:
  postgres_database: